const APPWRITE_API_URL = import.meta.env.NUXT_PUBLIC_API_URL;
const APPWRITE_API_KEY = import.meta.env.NUXT_API_SECRET;
const APPWRITE_STORAGE_ID = import.meta.env.NUXT_STORAGE_ID;
const APPWRITE_DB_ID = import.meta.env.NUXT_DB_ID;
const COLLECTION_TASK = import.meta.env.NUXT_COLLECTION_TASK;
const COLLECTION_PRODUCT = import.meta.env.NUXT_COLLECTION_PRODUCT;
const COLLECTION_MATERIAL = import.meta.env.NUXT_COLLECTION_MATERIAL;
const COLLECTION_EQUIPMENT = import.meta.env.NUXT_COLLECTION_EQUIPMENT;
const COLLECTION_STAFF = import.meta.env.NUXT_COLLECTION_STAFF;
const COLLECTION_ROLE = import.meta.env.NUXT_COLLECTION_ROLE;
const COLLECTION_EQUIPMENT_TYPE = import.meta.env
  .NUXT_COLLECTION_EQUIPMENT_TYPE;
const COLLECTION_REQUIRED_EQUIPMENT = import.meta.env
  .NUXT_COLLECTION_REQUIRED_EQUIPMENT;
const COLLECTION_REQUIRED_MATERIALS = import.meta.env
  .NUXT_COLLECTION_REQUIRED_MATERIALS;
const COLLECTION_REQUIRED_STAFF = import.meta.env
  .NUXT_COLLECTION_REQUIRED_STAFF;

export {
  APPWRITE_API_URL,
  APPWRITE_API_KEY,
  APPWRITE_STORAGE_ID,
  APPWRITE_DB_ID,
  COLLECTION_TASK,
  COLLECTION_PRODUCT,
  COLLECTION_MATERIAL,
  COLLECTION_EQUIPMENT,
  COLLECTION_STAFF,
  COLLECTION_ROLE,
  COLLECTION_EQUIPMENT_TYPE,
  COLLECTION_REQUIRED_EQUIPMENT,
  COLLECTION_REQUIRED_MATERIALS,
  COLLECTION_REQUIRED_STAFF,
};
